Repository WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-A, pull requests merged in 2024-11, with the labels that each got.

#35 Feature/carousel avatar
  client/public/img/freepik-apollon1.png
  client/public/img/freepik-artemis1.png
  client/public/img/freepik-dionysos1.png
  client/public/img/freepik-gracefully1.png
  client/public/img/freepik-zeus1.png
  client/src/components/CarouselWrapper.tsx
  client/src/components/competitor/AvatarCarousel.tsx
  client/src/components/competitor/CarouselProfession.tsx
  client/src/pages/CreateCharacterPage.tsx
Labels: REVIEWED

#38 api/chore: remove unneccesary entity relations as GQL fields to clean…
  api/src/competitor/competitor.entity.ts
  api/src/god/god.entity.ts
  api/src/image/image.entity.ts
  api/src/profession/profession.entity.ts
  api/src/trial/trial.entity.ts
Labels: REVIEWED

#40 Feature/real jobs avatars
  api/src/db/db-client.ts
  api/src/db/seed-data/profession.json
  api/src/image/image.entity.ts
  api/src/profession/profession.entity.ts
  api/src/profession/profession.resolver.ts
  client/public/img/professions/alchimiste.png
  client/public/img/professions/architecte.png
  client/public/img/professions/forgeron.png
  client/public/img/professions/marchand.png
  client/public/img/professions/matelot.png
  client/public/img/professions/philosophe.png
  client/src/components/competitor/CarouselProfession.tsx
  client/src/generated/graphql-types.ts
  client/src/pages/CreateCharacterPage.tsx
  client/src/schema/queries.ts
Labels: REVIEWED

#39 Feature/carousel god
  api/src/god/god.resolver.ts
  api/src/god/god.type.ts
  api/src/image/image.resolver.ts
  api/src/index.ts
  api/src/trial/trial.entity.ts
  api/src/trial/trial.resolver.ts
  client/public/img/competitors/avatars/1.png
  client/public/img/gods/aphrodite.png
  client/public/img/gods/apollon.png
  client/public/img/gods/ares.png
  client/public/img/gods/artemis.png
  client/public/img/gods/athena.png
  client/public/img/gods/demeter.png
  client/public/img/gods/dionysos.png
  client/public/img/gods/eros.png
  client/public/img/gods/fq.png
  client/public/img/gods/freepik__adorable-cargerge.png
  client/public/img/gods/hades.png
  client/public/img/gods/hephaistos.png
  client/public/img/gods/hera.png
  client/public/img/gods/hermes.png
  client/public/img/gods/hestia.png
  client/public/img/gods/persephone.png
  client/public/img/gods/poseidon.png
  client/public/img/gods/zeus.png
  client/public/img/trials/boxe.png
  client/public/img/trials/course-a-pied.png
  client/public/img/trials/javelot.png
  client/public/img/trials/lancer-de-disque.png
  client/public/img/trials/lutte.png
  client/src/components/CarouselWrapper.tsx
  client/src/components/competitor/AvatarCarousel.tsx
  client/src/generated/graphql-types.ts
  client/src/pages/ChooseGodPage.tsx
  client/src/pages/CreateCharacterPage.tsx
  client/src/schema/queries.ts
  package.json
Labels: CORRECTIONS DONE

#41 Feature/creating player
  api/src/competitor/competitor.entity.ts
  api/src/competitor/competitor.resolver.ts
  api/src/db/db-client.ts
  api/src/db/seed-data/image.json
  api/src/profession/profession.entity.ts
  client/public/img/competitors/avatars/2.png
  client/public/img/competitors/avatars/3.png
  client/public/img/competitors/avatars/4.png
  client/public/img/competitors/avatars/5.png
  client/public/img/competitors/avatars/6.png
  client/public/img/competitors/avatars/7.png
  client/src/components/competitor/StatsCharacter.tsx
  client/src/contexts/CharacterContext.tsx
  client/src/generated/graphql-types.ts
  client/src/pages/CreateCharacterPage.tsx
  client/src/schema/mutations.ts
  client/src/schema/queries.ts
Labels: REVIEWED

#42 Dynamisation de la page
  api/src/combat/combat.entity.ts
  api/src/combat/combat.resolver.ts
  api/src/competitor/competitor.entity.ts
  api/src/god/god.entity.ts
  api/src/modifier/modifier.entity.ts
  api/src/modifier_assignment/modifierAssignment.entity.ts
  api/src/profession/profession.entity.ts
  api/src/trial/trial.entity.ts
  client/src/generated/graphql-types.ts
  client/src/pages/StartTrialPage.tsx
  client/src/schema/queries.ts
Labels: REVIEWED

#43 Feature/stats details
  api/src/combat/combat.entity.ts
  api/src/combat/combat.resolver.ts
  api/src/combat/combat.utils.ts
  api/src/competitor/competitor.entity.ts
  api/src/db/db-client.ts
  api/src/god/god.entity.ts
  api/src/modifier/modifier.entity.ts
  api/src/modifier_assignment/modifierAssignment.entity.ts
  api/src/profession/profession.entity.ts
  api/src/trial/trial.entity.ts
  client/src/generated/graphql-types.ts
  client/src/main.tsx
  client/src/pages/StartTrialPage.tsx
  client/src/pages/StatisticsDetailPage.tsx
  client/src/pages/StatisticsPage.tsx
  client/src/schema/queries.ts
Labels: CORRECTIONS DONE, REVIEWED

#44 Feature/stats bonus visual
  client/src/components/GodsList.tsx
  client/src/components/competitor/CarouselProfession.tsx
  client/src/components/competitor/StatsCharacter.tsx
  client/src/contexts/CharacterContext.tsx
  client/src/pages/ChooseGodPage.tsx
  client/src/pages/CreateCharacterPage.tsx
Labels: REVIEWED

#45 Feature/modale resulta detail
  client/src/components/competitor/CarouselProfession.tsx
  client/src/components/trial/ModaleResultDetail.tsx
  client/src/components/trial/ModaleResultTrial.tsx
  client/src/generated/graphql-types.ts
  client/src/pages/CreateCharacterPage.tsx
  client/src/pages/StartTrialPage.tsx
Labels: REVIEWED

#46 feature/client scss de la page choix du dieu
  client/src/components/CarouselWrapper.tsx
  client/src/components/competitor/AvatarCarousel.tsx
  client/src/pages/ChooseGodPage.tsx
Labels: REVIEWED

#47 Feature/images
  client/public/img/competitors/avatars/1.png
  client/public/img/competitors/avatars/2.png
  client/public/img/competitors/avatars/3.png
  client/public/img/competitors/avatars/4.png
  client/public/img/competitors/avatars/5.png
  client/public/img/competitors/avatars/6.png
  client/public/img/competitors/avatars/7.png
  client/public/img/competitors/avatars/8.png
  client/public/img/competitors/avatars/avatar.png
  client/public/img/competitors/battle/'.png
  client/public/img/competitors/battle/1.png
  client/public/img/competitors/battle/2.png
  client/public/img/competitors/battle/3.png
  client/public/img/competitors/battle/5.png
  client/public/img/competitors/battle/6.png
  client/public/img/competitors/battle/7.png
  client/public/img/competitors/battle/8.png
  client/public/img/competitors/trial/char.png
  client/public/img/course_de_de_char.png
  client/public/img/gods/aphrodite.png
  client/public/img/gods/ares.png
  client/public/img/gods/artemis.png
  client/public/img/gods/athena.png
  client/public/img/gods/carousel/aphrodite.png
  client/public/img/gods/carousel/apollon.png
  client/public/img/gods/carousel/ares.png
  client/public/img/gods/carousel/artemis.png
  client/public/img/gods/carousel/athena.png
  client/public/img/gods/carousel/demeter.png
  client/public/img/gods/carousel/dionysos.png
  client/public/img/gods/carousel/eros.png
  client/public/img/gods/carousel/hades.png
  client/public/img/gods/carousel/hephaistos.png
  client/public/img/gods/carousel/hera.png
  client/public/img/gods/carousel/hermes.png
  client/public/img/gods/carousel/hestia.png
  client/public/img/gods/carousel/persephone.png
  client/public/img/gods/carousel/poseidon.png
  client/public/img/gods/carousel/zeus.png
  client/public/img/gods/demeter.png
  client/public/img/gods/dionysos.png
  client/public/img/gods/eros.png
  client/public/img/gods/hephaistos.png
  client/public/img/gods/hermes.png
  client/public/img/gods/hestia.png
  client/public/img/gods/persephone.png
  client/public/img/gods/poseidon.png
  client/public/img/gods/zeus.png
  client/src/generated/graphql-types.ts
Labels: REVIEWED

#48 HOTFIX: correct god image folder location, correct types to allow for…
  client/public/img/gods/aphrodite.png
  client/public/img/gods/apollon.png
  client/public/img/gods/ares.png
  client/public/img/gods/artemis.png
  client/public/img/gods/athena.png
  client/public/img/gods/demeter.png
  client/public/img/gods/dionysos.png
  client/public/img/gods/eros.png
  client/public/img/gods/hades.png
  client/public/img/gods/hephaistos.png
  client/public/img/gods/hera.png
  client/public/img/gods/hermes.png
  client/public/img/gods/hestia.png
  client/public/img/gods/persephone.png
  client/public/img/gods/poseidon.png
  client/public/img/gods/zeus.png
  client/src/components/CarouselWrapper.tsx
  client/src/pages/ChooseGodPage.tsx
Labels: REVIEWED
