Repository WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-A, pull requests merged in 2024-10, with the labels that each got.

#12 Feature/project setup
  .gitignore
  .husky/pre-commit
  .prettierrc
  api/.prettierrc
  api/eslint.config.mjs
  api/package-lock.json
  api/package.json
  api/tsconfig.json
  client/.env.sample
  client/.gitignore
  client/.prettierrc
  client/README.md
  client/eslint.config.js
  client/index.html
  client/package-lock.json
  client/package.json
  client/public/vite.svg
  client/src/App.css
  client/src/App.tsx
  client/src/assets/react.svg
  client/src/index.css
  client/src/main.tsx
  client/src/vite-env.d.ts
  client/tsconfig.app.json
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
  package-lock.json
  package.json
Labels: CORRECTIONS DONE

#19 Feature/api setup
  .gitignore
  api/.env.sample
  api/package-lock.json
  api/package.json
  api/src/db/db-client.ts
  api/src/god/god.entity.ts
  api/src/god/god.resolver.ts
  api/src/index.ts
  api/tsconfig.json
Labels: REVIEWED

#18 Feature/client setup
  client/.env.sample
  client/.prettierrc
  client/codegen.ts
  client/index.html
  client/package-lock.json
  client/package.json
  client/postcss.config.js
  client/public/favicon.ico
  client/public/vite.svg
  client/src/App.tsx
  client/src/assets/images/.gitkeep
  client/src/assets/react.svg
  client/src/components/GodsList.tsx
  client/src/contexts/.gitkeep
  client/src/generated/graphql-types.ts
  client/src/index.css
  client/src/main.tsx
  client/src/pages/.gitkeep
  client/src/schema/mutations.ts
  client/src/schema/queries.ts
  client/src/services/connexion.ts
  client/tailwind.config.js
  client/tsconfig.app.json
  client/vite-env.d.ts
  package-lock.json
  package.json
Labels: CORRECTIONS DONE, REVIEWED

#26 Feature/aboutus
  client/src/main.tsx
  client/src/pages/AboutUsPage.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/RulesPage.tsx
Labels: REVIEWED

#27 Feature/page creat character stats
  client/package-lock.json
  client/package.json
  client/src/components/competitor/StatsCharacter.tsx
  client/src/main.tsx
  client/src/pages/CreateCharacterPage.tsx
  client/src/pages/HomePage.tsx
  client/tailwind.config.js
Labels: CORRECTIONS DONE, REVIEW REQUESTED

#32 Feature/carousel job
  client/public/img/arrowL.png
  client/public/img/arrowR.png
  client/public/img/dalleForge1.png
  client/public/img/dallePhilosopher1.png
  client/public/img/dalleSailor1.png
  client/src/components/competitor/CarouselProfession.tsx
  client/src/components/competitor/StatsCharacter.tsx
  client/src/pages/CreateCharacterPage.tsx
Labels: CORRECTIONS DONE, REVIEWED

#33 Origin/feature/front trial
  client/public/img/course_de_de_char.png
  client/src/components/competitor/StatsCharacter.tsx
  client/src/contexts/CharacterContext.tsx
  client/src/main.tsx
  client/src/pages/ChooseGodPage.tsx
  client/src/pages/CreateCharacterPage.tsx
  client/src/pages/HomePage.tsx
Labels: REVIEWED

#34 Feature/results page
  api/src/combat/combat.entity.ts
  api/src/combat/combat.resolver.ts
  api/src/competitor/competitor.entity.ts
  api/src/db/db-client.ts
  client/src/generated/graphql-types.ts
  client/src/main.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/StatisticsPage.tsx
  client/src/schema/queries.ts
Labels: Conflict Resolved, REVIEWED
